services:
  - type: web
    name: clinic-margin-analyzer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python clinic_dash_app_complete_final.py
    envVars:
      - key: PORT
        value: 10000
