services:
  - type: web
    name: clinic-margin-analyzer
    runtime: python
    pythonVersion: "3.9.18"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn
    startCommand: gunicorn --workers 4 --bind 0.0.0.0:$PORT clinic_dash_app:server
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHONPATH
        value: "."
      - key: DASH_DEBUG
        value: "false"
